(:name           "tgsgapcloser")
(:repo           "taffish-org/tgsgapcloser")
(:author         "KaiyuanHan")
(:version        "1.2.1")
(:intro          "A gap-closing software tool that uses long reads to enhance genome assembly.")
(:dependencies)
(:functions      "tgsgapcloser")
